
import React from 'react';
import { Download, Sparkles, Share2 } from 'lucide-react';
import { motion } from 'framer-motion';

// Vidstack Imports
import '@vidstack/react/player/styles/default/theme.css';
import '@vidstack/react/player/styles/default/layouts/video.css';
import { MediaPlayer, MediaProvider } from '@vidstack/react';
import { defaultLayoutIcons, DefaultVideoLayout } from '@vidstack/react/player/layouts/default';

const VideoPlayer = ({ videoUrl, prompt }) => {

  const handleDownload = () => {
    const a = document.createElement('a');
    a.href = videoUrl;
    a.download = `xplainer-${Date.now()}.webm`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <motion.div 
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="w-full my-4"
    >
        {/* Main Card Container */}
        <div className="relative bg-[#0f111a] border border-white/10 rounded-3xl overflow-hidden shadow-2xl shadow-purple-900/20 group">
            
            {/* Header - Glassmorphism (Optional, kept for branding) */}
            {/* We might want to remove this if it conflicts with Vidstack's top controls, 
                but let's keep it as an "overlay" for now. 
                Vidstack usually puts controls at the bottom or fades them. 
                I'll keep it but ensure pointer-events are managed. 
            */}
            <div className="relative  p-4 bg-gradient-to-b from-black/80 via-black/40 to-transparent flex justify-between items-start pointer-events-none">
                <div className="flex items-start space-x-3 pointer-events-auto">
                    <div className="p-2 bg-purple-600/20 backdrop-blur-md rounded-xl border border-purple-500/20 text-purple-400">
                        <Sparkles className="w-5 h-5" />
                    </div>
                    <div>
                        <h3 className="text-white font-medium text-lg leading-tight drop-shadow-md line-clamp-2 max-w-md">
                            {prompt}
                        </h3>
                        <p className="text-purple-300/80 text-xs font-medium uppercase tracking-wider mt-1">
                            Generated by Xplainer AI
                        </p>
                    </div>
                </div>
            </div>

            {/* Video Container with Vidstack */}
            <div className="relative aspect-video bg-black z-0">
                {/* <MediaPlayer 
                    title={prompt} 
                    src={{ src: videoUrl, type: 'video/webm' }}
                    playsInline
                    className="w-full h-full"
                >
                    <MediaProvider />
                    <DefaultVideoLayout icons={defaultLayoutIcons} />
                </MediaPlayer> */}
                <video src={videoUrl} controls className="w-full h-full" />
            </div>

            {/* Footer Actions */}
            <div className="bg-[#131620] border-t border-white/5 p-4 flex items-center justify-between relative z-10">
                <div className="text-xs text-slate-500 font-medium">
                    {/* 1080p • 60fps • Neural Audio */}
                </div>
                
                <div className="flex items-center space-x-3">
                    <button 
                        className="text-slate-400 hover:text-white hover:bg-white/5 px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center space-x-2"
                    >
                        <Share2 className="w-4 h-4" />
                        <span>Share</span>
                    </button>

                    <button 
                        onClick={handleDownload}
                        className="bg-purple-600 hover:bg-purple-500 text-white px-5 py-2 rounded-xl text-sm font-medium shadow-lg shadow-purple-900/20 hover:shadow-purple-500/40 hover:-translate-y-0.5 transition-all flex items-center space-x-2"
                    >
                        <Download className="w-4 h-4" />
                        <span>Download</span>
                    </button>
                </div>
            </div>
        </div>
    </motion.div>
  );
};

export default VideoPlayer;
