import React, { useEffect } from 'react';
import { Download, X, Sparkles } from 'lucide-react';
import { timeAgo } from '../../hooks/useVideos';

/** Full-screen player for a generated video. */
const VideoPlayer = ({ video, onClose, onDownload }) => {
  useEffect(() => {
    const onKey = (e) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  if (!video) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm sm:p-8"
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="ff-fade-up w-full max-w-4xl overflow-hidden rounded-2xl border border-line-strong bg-ink-900 shadow-2xl"
      >
        {/* Header */}
        <div className="flex items-start gap-3 border-b border-line px-5 py-4">
          <span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-accent-soft text-accent-fg">
            <Sparkles className="h-4 w-4" />
          </span>
          <div className="min-w-0 flex-1">
            <h3 className="truncate text-[15px] font-semibold text-mist-100">{video.prompt}</h3>
            <p className="mt-0.5 text-[12px] text-mist-400">
              Generated by Xplainer · {timeAgo(video.createdAt)}
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-mist-400 transition-colors hover:bg-ink-800 hover:text-mist-100"
            aria-label="Close player"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Video */}
        <div className="aspect-video w-full bg-black">
          <video src={video.videoUrl} controls autoPlay className="h-full w-full" />
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end border-t border-line px-5 py-3.5">
          <button
            onClick={() => onDownload(video)}
            className="flex items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-[13.5px] font-semibold text-on-accent transition-colors hover:bg-accent-strong"
          >
            <Download className="h-4 w-4" />
            Download
          </button>
        </div>
      </div>
    </div>
  );
};

export default VideoPlayer;
